apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ukkzap8vb-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ukkzap8vb-java-quarkus-gitops